### ISSUE TITLE
Cluster not deleting

### ISSUE THREAD

**Issue by LawJolla** [graphcool/prisma-cloud-feedback#12]
I tried to delete a cluster (because I'm not bright and put my database in the wrong region), but it's stuck on "Deleting."

**Comment by marktani** [comment]
Do you remember your cluster name?

**Comment by peterschussheim** [comment]
I have this issue as well.  I can create a separate issue if needed.  In my case, the `cluster` name is **notes-prisma-cloud**.

**Comment by LawJolla** [comment]
Just to update, I tried to make a new cluster but was told "only one available cluster during trial."  I now have two clusters ... `prisma-demo` as "Deleting" and a second cluster, also named `prisma-demo` as "Healthy."

Curiously, I didn't name my second cluster `prisma-demo`, so I'm not sure where that name came from.

**Comment by timsuchanek** [comment]
We resolved the issue for @LawJolla 's cluster. @peterschussheim is it still an issue?

**Comment by peterschussheim** [comment]
Hi Tim,

yes this is still an issue.  Just tried initiating a delete and see the same behavior (cluster not actually deleted).

**Comment by timsuchanek** [comment]
I just deployed a fix, can you try again @peterschussheim ?

**Comment by timsuchanek** [comment]
@peterschussheim just wrote you in Slack, let's continue there, that's quicker :)

**Comment by LawJolla** [comment]
I still have the issue.  The cluster no longer shows, but I still cannot create a new one.  Error:

```
GraphQL error: You already have cluster "prisma-demo" provisioned in workspace "Dennis Walsh". In the Cloud Beta you can only create one cluster.
```
